In [20]:
import torch
torch.__version__
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 3050 Ti Laptop GPU'

In [21]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [6]:
x = torch.zeros([2,5])

In [8]:
print(x) 

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [9]:
x.shape

torch.Size([2, 5])

In [11]:
y = torch.rand([2,5])
y

tensor([[0.5983, 0.6847, 0.6245, 0.8192, 0.0457],
        [0.0010, 0.6371, 0.2683, 0.8069, 0.5592]])

In [13]:
y = y.view([1,10])
y

tensor([[0.5983, 0.6847, 0.6245, 0.8192, 0.0457, 0.0010, 0.6371, 0.2683, 0.8069,
         0.5592]])